apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
generators:
  - secret-
resources:
  - namespace.yaml
  - ../../secrets/authentik-secret.enc.yaml
helmCharts:
  - name: authentik
    releaseName: authentik
    version: "2026.8.3"
    repo: https://charts.goauthentik.io
    valuesFile: values.yaml
