apiVersion: ENC[AES256_GCM,data:q0Y=,iv:m72bwcpYal2tQqF8jw9y2PilpFW/iw1FeMV85TWEFlw=,tag:7x0rPMn07+/u/uu12K9FbA==,type:str]
kind: ENC[AES256_GCM,data:EumPOI2Z,iv:HdNLpfPcfeGn2ngY8CCRd/iMFS9JVBb0fMXhoBsI8Cc=,tag:2yMvKyMJ9YU6wIpcWdhJaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u4TIICKzbamYSO1aYI78T+I=,iv:DkqPHWmWwCE7IZzPuetdYi+b+nEAqiZrSqiKCqBvGNs=,tag:ujyvj5hLcEJsYcAHqdGO/Q==,type:str]
    namespace: ENC[AES256_GCM,data:gmbd6xwU0f0h,iv:cu1Z0qCh4Nt+NePyrD2i3fCOdks5wpW436Ij+qNozuw=,tag:UO43J1SilWAiE/SLJ9q/HQ==,type:str]
type: ENC[AES256_GCM,data:Q6qwIq/l,iv:WaFSrodgRI2syMOi3elzljm+eT2N8HyQtka6zy0CHCg=,tag:4LlH0sjrCgkO2eOS2Ttcog==,type:str]
stringData:
    secret_key: ENC[AES256_GCM,data:mubhANvzFAHuToZSSRhaaXAXtgT5KigelKUTjv9OquRZ0gMGAuAyoI1oh/jYkUeLNacVMJliTLoD8djfvrWoDCgiQYXM2K411mOZUv5SJN0=,iv:CBKN7+RpkOh3NSa7ir+Bw7SwOmV8+kq+Gtcq/3sTXUM=,tag:4U58tXl0Ht6NEdMdzcSzOA==,type:str]
    postgresql__password: ENC[AES256_GCM,data:9XogMMN+ofb0UPYmshaZfzFVriM77FhyrX29OuN78n9lKJevZhHQ+rcdiKs29aF8iS2oniS4+SXb8lOKtudDwu0YBGbs7rDPKuZjwzCvi34=,iv:4jm17dJ/esS25TUw3eKVGECJuktnOIvxAGK2TnGLIXw=,tag:FJerarBJU3Td9naIeRNRUA==,type:str]
#ENC[AES256_GCM,data:7L8vdk6gSosGi2YUc6bpFpO3TQODsfM=,iv:GOFctgXye6qvpOpisBPpVKKSWIGzCBOfo+qhc5SkaH4=,tag:1l3fvwiXsIiYg3a0+FTDLg==,type:comment]
#ENC[AES256_GCM,data:+fCGW19zZvzwdRbutD4luvzfNvM32fG9RnPt5iFf,iv:kQZIXXmHgBW5+uRkKBVrIUmSR/heZ0KhgsJNZrQnI10=,tag:aZpddI6oK7gm/B/aFwgYpg==,type:comment]
#ENC[AES256_GCM,data:m+sXD8vR+Np8J4rCH9hW1xJCbt8X65iPfyGCijsX5AQ=,iv:MeliaD6eWBni9pBmfmeu2QXtBmOmM1ULG2bO7wgdG7w=,tag:Eynvki4kPdJ6f9gXtJFwpg==,type:comment]
#ENC[AES256_GCM,data:CKiyncDXeLD+yxyMf8SjswfWrw==,iv:VSokwiU2djNZV5E4gVWnIZX3Y9PXE3JUhf5kBSmRDdw=,tag:ehyCxFa+9SzHOeRjmE2k+w==,type:comment]
#ENC[AES256_GCM,data:XmhQONNkfWDTu4tjDnF4BqHbWYEde6rnJYVqGw0RgLE6DCHxFZNbTKhkRg18Gw==,iv:dj+1xC0S3N4eonRkJV4xNGhswM6ZNoLe3RDPgqa/D3s=,tag:+fqUz3s3ZRWeS3Eq4iu0Iw==,type:comment]
#ENC[AES256_GCM,data:aGEeCieC1NJCpTsT4gigbfSE+Z9Sglm8rFUcpePyLCeyHlrM5Ntmgrja2hZ47Q==,iv:oXkKFEsA+gDXS8tOg07Dg17PiiVoOZyMsBknuucSdqQ=,tag:5dPu9FnXWLaxWSJuErEYDQ==,type:comment]
#ENC[AES256_GCM,data:SjSLn7FS19qOhbM4tiCHyosCLc9+FUs=,iv:f6ORdtGmImcHbnE1/dp39Ia9qh8yNhcnW162utyjq8I=,tag:BDkaaK5XJDdAJERIxbNArw==,type:comment]
#ENC[AES256_GCM,data:cilzbZ1XGwLZJB7qQHEOgFuHpzpBACyC,iv:Psll3J7U6C9wzZlHQhrOiI5dFftacmG3/9VYxcW+LMc=,tag:doZ0eyHQlQhUMIypaRgd7Q==,type:comment]
#ENC[AES256_GCM,data:A/vxbppzwl/WjAOwZnzquQ0FiidOwVRG2DHsK8omjpOzB7RKgg==,iv:dMwHncw46SNUHcaOx9H9gNBH86zxuVWIsKZY5OGfAUk=,tag:lS/3imcIwXh0LNaPpOyAtw==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudmV6VjAyQ2R3R0dqbWJ1
            RnJPOHNENVErYzJqTlJSNjBNeU1KaW1PSXowCkI5MzBuU3BrWWtQeUV0ZXdCL2Uy
            R3YvZFByS0lNTlZUQnQya0c1eUgzVGcKLS0tIGtQQWFHcVo1OS84Ry9MNnk3V1d5
            OU1Nc3doaFRrb29ubmdObU1sRjJNazgKJHtPlqY0nrtlPobgeERfFhyCe8/i7iDa
            RBLBJuG4ne9WnN1adjfvVz9N/hpkQv9tOmxMrkwqIKTqnFcoJHWIfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-10-03T19:29:16Z"
    mac: ENC[AES256_GCM,data:VrZUf5u/XfbcPKVw0aAVRxQFwqk/uf8K3414gfZ6sZZlH7y0ffi7F9MfwHdBlIuZX1o/8F+pkTRBM022xzxu4OHCdzv9504CI9ZismM+2qemc1FJyK1WEMTPkva7vSVY+OtdafJFgdtUgK81/qnq/5ER4wfH7MLeQmeJJlJsw/w=,iv:e7hnYJ07L/I/NJsxxPKeAwsfijdJsyFNaVgHjo3BkkU=,tag:mUwTvurWLUfPUua+5fx3ZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
