apiVersion: ENC[AES256_GCM,data:fR8=,iv:noW62ZSTWMJthAVESoa2HT/knliYZ6vIg+jYQos0lig=,tag:zMZPhOLWB2tvpUvzGN63hg==,type:str]
kind: ENC[AES256_GCM,data:PyJCoDM2,iv:kn05NZgGXiC6SUpq6d7eyTszr2DZCUyX6PM6HH6A9Ig=,tag:our6AiXGfbDpmaA0B0SfEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UoJFztrU+QNcpeQJII+jifA=,iv:r0cIX+oLLJkwVZqGSKKAWRsADKqgSlscSQK1fYDUbi0=,tag:6XkI4lgVx26kv8CuYemmqA==,type:str]
    namespace: ENC[AES256_GCM,data:7rt9OQTEUcre,iv:4BpcO4id0SKnCP5RS2UBXfkuFqOg8JRwuQIOFxgGv5o=,tag:M6F01G249WjyTUEf+Xn+fQ==,type:str]
type: ENC[AES256_GCM,data:Lap9NMqO,iv:SUyanLQN+JEK3shp9uAKSDJq0RcNFD4kNuy8AZt9bEI=,tag:vRU6LnX5bPhpc4VKPwyNOQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6dLsKyVgDOp6vwof+9KuMK6AwZIUL0E+7Nq6H0pxnRKX48ND5XblehbWvuQyCiSTSZz2GQr6rEZtb+RC9r19r1HjbYvZjJF+DmdCy//AWEE=,iv:kbkcKHuSNAzKWsQfyLepSlfzN1Dyku32Ftzr0TrJqCQ=,tag:8YPsUkBMuzIdyF9nvVNKXA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:D1mWLvJXAIz4QMdE5IyItFs0g7t5cqrELn95+djtM/McAg1d2QbQu16cL32rQqFaffEN4sWSvpBJ5Z1OOL+Av4SgXLfZTtsWOMd+dwOXzf0=,iv:S2AxpmTA9TnG5vL3OPHUOgZ0htbOAut9mqAwyjCl6Bw=,tag:fdfFbukS244BTYEQ0LmGzQ==,type:str]
#ENC[AES256_GCM,data:5eGUZofe9Svg/gp8bXsticvalB9ADwA=,iv:R0ZnRYbF+HWQW+6mbsLW7XtWOi9GNqa5q5PN6QazSc8=,tag:wzXBtswg3kdyz7pX8Das8A==,type:comment]
#ENC[AES256_GCM,data:xWvkbCp9Qj/QtrtFyymurDJ+pKz9XA9oP9bfzjA1,iv:1GJF21HUW7dSlRdHGjc6aFI61JF1ObnKX9XqPT98bnY=,tag:qu0SA6sW6lAALUwOL+4yAQ==,type:comment]
#ENC[AES256_GCM,data:lZRtHgfXzbbu+Or8oDwrf/UF/ItHI05CNF96GARno+o=,iv:aqfxKOFV3F3/kaV8xqD9CQpF8PzoArxMPNDVZPMn7q0=,tag:EFkzIp7X7yscrV1gqn4d7Q==,type:comment]
#ENC[AES256_GCM,data:mqC5suRp7In58War/b9phchfTA==,iv:QIv4zqvLxX0MvkPr8WPNtF6CzJR+gySsppyB52yQV9k=,tag:s2nyegdRRgY86qBo25KX3w==,type:comment]
#ENC[AES256_GCM,data:nb0F6zMEBB4YGazNDIhVtMjU6b6TPxemkWG0u6GJ5EJXqgARjUXg7QHkq+W7Rw==,iv:HkJms67nKVv2nCpreZB9joJHWon5AjvWzYhRItLn478=,tag:NCESO5jP84uAOhpbIoch8A==,type:comment]
#ENC[AES256_GCM,data:cOm0qmOQXqnsetAyMYvgH+RX631LiUx9l5Yp8j9oiPsliAMzy6JzhKlkYKINNQ==,iv:7NgLgpLe2gc0EdirhKhYt3MqKa3GmCMhJbrkYQgNo/o=,tag:DajVFVQgYq/CIpxJ7Z7W+w==,type:comment]
#ENC[AES256_GCM,data:IoM4D/174hCZCaVBWtJKm4MHmTNDkp8=,iv:DHOaC4uexiEmlx0nhTrnntE3BFP1IPI3tmfRHI5d8x0=,tag:EHIaGadsbsd+pMe1TP3O5A==,type:comment]
#ENC[AES256_GCM,data:9p197wk8z8XiOYthOPFh+qLyA9e5jtKM,iv:mfBUq/w9xtwddK7Vsp+WPWY6aET+ven+XmPp3q0H7g0=,tag:90eYRyaBL3tV3p+vR35UfQ==,type:comment]
#ENC[AES256_GCM,data:/+LM/QF/xayEbcxmeK9wT0wFShCt9Z9dRl7gCdacuX9xsvg1NA==,iv:Hc7VfLLTZXW7Aqwf0qP6pKQie8Gqt8Ra00h4tfQSr78=,tag:1HCycslx3L6ykiXKZGooag==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2elhmMWRhT2swZWJQRjZ5
            ZGxqWmVlcURzbjNFOVI2Z2NET2tqUXNlN1ZNCkpqQ0s1c1M2K24ybS8ySjh6Tjc0
            bkRqM3kyQVhxTnhYSEtqdTdKeGpMVk0KLS0tIHFFUlJPL1JCclpCeTBiZ3VBZFVU
            MG81YkpiTVorSG9kb2JlakZGM1BScmMKagI0Wk6gGPP2cQeefatSHrvs7P5B+LlF
            A2XD8+p0WxXcWv6BqJDBE+yGaaS4VtJ38W/c/H48dt+CFS5IFOUTAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-10-04T21:15:33Z"
    mac: ENC[AES256_GCM,data:b03g/QZjoWbF4CNDzkGg9Ph/2b8wTXaSrqqvH1APacBz4LeAU2fPOED5Hoi1tNjHpjhrXzKTsuqnk8V9p27VHdA6HkqyvR9Ss9HCn2Pmt86d4wmqUShSIiebpzolbieK6dQEkbvVlURbb3rO+P8wCFfo2fI/OL8cylm7mJ6Rskw=,iv:gHw9fFlq19Rx+uQWUKdEFK6znFzAe3FUXtLntFSOzh8=,tag:3Qog8VqA0lUet+PITa9MKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
