apiVersion: ENC[AES256_GCM,data:jqE=,iv:lnExvEDY6wOhh+3WYwkzt+c5xeNvgA38cM/+98mPFaM=,tag:AL8ww9BJPhB/g9YwY7d4xA==,type:str]
kind: ENC[AES256_GCM,data:Bc7jsHCt,iv:POvLuIxpl88YHIuNR96tOF7leAIVU7LRxhMSomRst6Q=,tag:Wt1Snw24pNYGrXrX1SECFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2E93RTs1xyO605+h5S/mdgM=,iv:ITruM1hqKK484d9zgrCS3KcSRkY/gncmSZn36ZDltwM=,tag:YgLMjOGX+dnpIFL0+JSN6Q==,type:str]
    namespace: ENC[AES256_GCM,data:oX3aSmsD/u6g,iv:vQDmtEJ2U+EPcQ1VX88g5hya/YdsCMtkvOF486RmbiU=,tag:BCQSV/mi+wHRd5z7hFxjQw==,type:str]
type: ENC[AES256_GCM,data:Ih0SLDj/,iv:+P9L+rT5dykWI5APn5bJ1gBbAFZ2HagUd1F+V9VQ6bI=,tag:JK116FPYI2sM4rZFDBsq2g==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:a1da/+lFG8LtDZLOyaN+OFFcKUY1YXxtfMHIclbZzwKauxXRBhRya/fBwGWmTkLJwdNEcvq5XiiW1Q7di4iK9XfDrmSKOqV11pc0/Ndz6xM=,iv:zC3fOCCVVMz5eDtlpC8EIY9Gzuw6yELUhZALYT8rqnw=,tag:4YL9egT3HDbje2zXjQ+3Qg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:/3GffQud/qF8YmiaG0D8lsOFNxi9vHMVNsxmYY0wsdB55EaLhm2n+1nrWyyq8x3Rmf8h6qQdd0b+0xb/DWgm96UaPsRZ5UtHPczJXySLkeY=,iv:zRBI34KXQ4WmlxwBTU+UMMpKUYFM1cVH9iSI4JfBp/I=,tag:xnHjN3oSmoayQ7uqxypo1w==,type:str]
    #ENC[AES256_GCM,data:gy3Pz3kBjDAngg==,iv:kG8Ld/PoDuplVIMr/ST0pdfNbGMNacbePaPifF8qQT8=,tag:c6OfJGHXXTZjM4oHFvxOYw==,type:comment]
    postgresql__password: ENC[AES256_GCM,data:EsTOwhoFWW8ATkgFTIk299RbVumLg4h2xULsULnKz6TWA5ytfac724nI8Q/KiMXaWZac+eGLUYUCzJy1uHXZtzz2pX3eT1FwDDGiy9PeVwQ=,iv:8ni5dOzYWfhP7qAd+cDhBpmIUMD4LZej3N+qlCoxRWY=,tag:2OxkJoK0uFC4d++zDp+WHA==,type:str]
#ENC[AES256_GCM,data:QJ2vfa0Ap/r5M9MOQ8saxM3/ZXEPK9I=,iv:Wgu7pb4vzmy09bVSqmo9bjW1Ex5aPWRKq0acdOOHrWI=,tag:qxEPxNsDzMjlBih/K1M7kw==,type:comment]
#ENC[AES256_GCM,data:42fMVnFBydteYXb48xlxqUzubfyYt2laaVe1oNUZ,iv:B62w8nGR+rXOpgOCF3Wq9wYlCQKmTlMbVmqsd0yUHDg=,tag:f8n2iERZ6zul1M0r8PSFHw==,type:comment]
#ENC[AES256_GCM,data:c+8NWiI6yLTz7Q1FRR9s4zNfpuh/jZXIkubbcsKNPec=,iv:vYHlIU/I/nhO5daQmAcLYFPx455DDZBSHgzmjpyoUjs=,tag:diztj7QkaQnOe+n9ZM+r6Q==,type:comment]
#ENC[AES256_GCM,data:sxq74MxrsHM8YF84rR5KBTDrRQ==,iv:oMQPKYuVF+UiVRg/BF4998kaqOtxfSWVOBwmrP88fUs=,tag:z2FXaf47P29f1didgrf2uA==,type:comment]
#ENC[AES256_GCM,data:K1vM57mmzE3gdKfkPIPijdLZggv5K+UI+GVrlTwA+xu+L4jWfC5LSQeIEiH3vQ==,iv:EUTC7jjFGUg6alT/4xVGykuE1NeGIRE4BLukDWEB0FQ=,tag:ONWVnEdE9stxVVJa4qIeYg==,type:comment]
#ENC[AES256_GCM,data:XFqhWBaexuG9ka4d41mvJ+5ISb3C7++Jp429tQGMto5JxczXpUbwqi6OHTWPxw==,iv:jmTSZKRB1c6DvR//mLDpAs8CVpbp06Matq/vZhu3BK8=,tag:+4YdoSJezX/j4OS4mjSapQ==,type:comment]
#ENC[AES256_GCM,data:M4aquM3iztFppJ+1+geIr5F2VSQwirs=,iv:ADzXRvkdyTR9y3ciMpi2inNrMKoqpa8HyoDbvY394x8=,tag:ue1Cuw7GGaD6jbL5GYUDcg==,type:comment]
#ENC[AES256_GCM,data:PAvIR9TEOQLwo11CNYagc2m/tBsBhZvH,iv:p+szWZ4g4EFCj8hLneqvjfoCenGROy2yRdLVH8DkTFM=,tag:NQddMCbTl88HaDqersQDlw==,type:comment]
#ENC[AES256_GCM,data:/M0/LxYHE6Kw4heAAZHIJbI/FHpee9IYZaV5tUSHTpZPmRlaTA==,iv:humI2IXx8gFDfK+Wj28sjMhgPsfWLrVZ1e6qUG+3omY=,tag:5xwpOLWtEd/VflpmZUHfUA==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVHBqYythQVVYS0NzK2k1
            Mk1RVFNJakI1R2svQXVLYjBmZDZiVEZPeEJnCmxjaEI0V2Z3alZURXV3K0xhN2Fq
            VUg2VDcrRXN6cGcrTFR4V2FodmVmQzgKLS0tIFZjMjBwamhOTVdKRzAvc1hyVlgx
            b0d2UXpKZVgvM1VTS0JDRTJVVEI1c1kKMpOmLldJ0+uWTOYw5T5cOOuhGJOrcMqH
            6JeagQiZMezERyU9kg3G/Lc3v3hfpDUSnM9AgEw4ppuL3QoTK25TVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-10-04T22:14:14Z"
    mac: ENC[AES256_GCM,data:ghSD3yPZ4gDNHjoAZwnhawtGxs+qYin+LocajKV/+M3k5XR6oSJtWetBOW5hBNtrLTbKnyaEwZ6D9o2jICk8pR98Ic1j0XzFaTix0QyT5HatDCiHNd9ONMm6R/Wudplvikp34YsxwsxhBX0t1/yzY016gQGmYHGGYVqj+6EY0YM=,iv:LvLCGHSYF44omh7jvQBqgSWtfEOya66OOLJnCdBSbsI=,tag:mNPkZwqzhNYfn/RteC5VEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
