apiVersion: ENC[AES256_GCM,data:iOs=,iv:hs2t+2E2w6AE76jpD2I24Yc1gM3Nb71op5Ccive/XP8=,tag:lCKC+Es3QqYcFu4mREs0/g==,type:str]
kind: ENC[AES256_GCM,data:cjHc7FvR,iv:q/EF83cuZT3OKtjxUVL1XtxvOUo9bw00xkXUwpqD42o=,tag:FV/GY8Ny5GObprZmsas1Qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5VN9EaVmW3FY2vuzZoY=,iv:BI9EU/6521/bRK2LoEPAB6x/+dFVUkq/Xn+yuV53qm8=,tag:ikH58e6J0k4Keu1aInvi5A==,type:str]
    namespace: ENC[AES256_GCM,data:gFsUz+cefUNR,iv:OUVS4Mw9eEXnytlBkgngk10z/u4dQHL3IgWjRsb52WQ=,tag:jWTliG/mU6mCgxI0Vxq2zQ==,type:str]
type: ENC[AES256_GCM,data:1XbrEu8l,iv:BOIHVU23QxOyqabq28Qe6YpicV84kM60soQiTD1uYRg=,tag:9iPPOC+Uo5mGw1+fJl2yqQ==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:nXmh+h0mEkW1UoQ+r9ngXRo=,iv:y+zls5G27ZpuToQzHD+KB6PgtXcY2oacQu0ShypHD6Y=,tag:LqyaYyX3GGOL/kc7Q1+xZA==,type:str]
    clientSecret: ENC[AES256_GCM,data:zQFQx04P7AkgIWpD1u7y1bLxAIu8eumlxZq55kz9Usju5ZAra9U4Fyz1J7njX7To9gGauDIZzUkjROa6Al6n,iv:rWNf5axUoLR2rk+akHQ1Vx8/iN/EChXHCCPmf1O8EaA=,tag:icO7goUu3bM1xSdxHwszBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNHhZUTRWK0pOcCs2ZFVL
            VzBZNFlrQzZIYmc5aU85TFptWkI5VmR6ZkdNCkRmK3VrNkw0LzdaeHFMSlBMa256
            cEFtSDl2SVFZa2V5MmNhYXh0MnNXa1kKLS0tIENxQ1BrS2NqQ0FidVBrblpRV2Qy
            SmdHcG1oRFU5RGVIYzU1cjUrYlNKa2MKQGspC3z+B5zU9v8aO/8tBqUlh7fHoQzi
            Wylo4VtblCtC8UcoSDWbHJMNNeurTkZpy/5sUYeza+EbUEteP3zlzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-10-06T01:31:39Z"
    mac: ENC[AES256_GCM,data:nWWdnJg3CkwYF3rIR7JOskuYkog1BIwpJjNoXJ9dBvB4u5cnHGP/VBP0wU18JmF6OMLPt0SL2bUxAZS5z+Ztgp1zRLCUK773q9Mrfp7pxb4ihQJmWtorQ3VANzFfn5JQdVuBQyLnMWVg5t6NMDjTRFuHMBm8lTdFpVeJlKgpBKw=,iv:iTb8hLMTW3WfEHTxv9yC//vhK28gPpXkHDdxJx3fJlA=,tag:Z6VEpqSlW+rmWd6ecx5iQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
