apiVersion: ENC[AES256_GCM,data:MQU=,iv:xmGqa1AU8nol8yejvTS9kQkFFA+9V/q6CQi0N8T0qW4=,tag:TGngzCAau5gRveL/3CcykQ==,type:str]
kind: ENC[AES256_GCM,data:DnbaGpRh,iv:E2AL8bXxG8iiQrhtUJnBPMi4ZO62duvydNobvGwby0w=,tag:P9uUvXvmLmI8C1hde5wfWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Fh469AZIFdI0NOJmcLk=,iv:o7ja5s9Vxo8E67JGGkJJXiAIQdohdarIm0UbnKJdhsQ=,tag:n6YTcoV4HB31I597w8fJSw==,type:str]
    namespace: ENC[AES256_GCM,data:+E//tLjRM3y3,iv:esiSIxrqQ2PSE6KiZTB1A0OQOussCU/c7f/ux6Ca6TE=,tag:yxEBY6jnFePqIkqW4s2wkw==,type:str]
type: ENC[AES256_GCM,data:9wGo0LsC,iv:EW9NCOm8kO8zx3eYc3Df1qA8ex71Fr4UXdflUYF9RDQ=,tag:6Js/I8vY41tULdzZDP+J1Q==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:yc9mNOaAQt5hNupygsRIZTk=,iv:Hcxh5eASgC06orWmzoa/iEX3LjAmhDWmBF9KLvzz9Gk=,tag:kHUw3jpaNU3J2mvuWauiFg==,type:str]
    client_secret: ENC[AES256_GCM,data:QGVZppOuSd7JBggSFy6t2HNqSOvfJTkWqvuVqGB1rXwwWKH5r6TcaJGXd/zPxyoP0GMaPZjoNsLu67aVQ/+D,iv:8WWx//D5XYUIAtlmlp4IxCC7UstFHOBQyoDHnG6N/KI=,tag:AeM4S75+EC0rxlMrQ06aDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWDBDbHU2R0ZPU0s3ZS8x
            Tis3MGhHcXYzR1VMd0FRTkoyZHJGbXg4dmtzCjdBdG1HeGlIM2plc2pBYmRNcHlB
            dU11TG9NdmxxbE9GUVh6N2lnMlRUeUkKLS0tIDhvUmh0QXUwbitBRXVJbFVtT3Mz
            YjF6em90cXV2S3VpOERBcWVYM2d5TGMKpdTfcVy8HNKwk8PQ0TKHZ63R0QwKxS1Y
            mlR1XzLnXmZ0+xv217OPlANAFgcmRkLfZZRayqEvizw58OeXkilinA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-10-06T01:37:18Z"
    mac: ENC[AES256_GCM,data:Bidl+NVJH5aM2t7OTrgV78not8bNbMkuHFvTM5DN/frNX2EZ8B4gHmA5ZPor0kX7ponpkKCcV87aXLP9frhgF6xCBV/UIYQYi4K66RVu2FgYf8H0Hsgjb1je04xwMv42S2luJFrKfA0Y8WcHsEDpB+8WPJF+glUgpp8EFAvghl8=,iv:zB3L9IzLQk95Dn/mrct35VAYbpRRECqeaZHTXZYR/SQ=,tag:i+PmdvU8+nBAL/vBOuFjfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
