apiVersion: ENC[AES256_GCM,data:g3w=,iv:KCNhHaRPLgrcArA49dMW8aUtMpH2tFHpx2rWHn5Y9YI=,tag:pJ+VDPBzkN0MMMHmdVP2UA==,type:str]
kind: ENC[AES256_GCM,data:J7H0bn+z,iv:pwplY6qjkLAa75vPC6awi3fbnHzY6D0q1bFAFWRalfE=,tag:WRWv8ZKyzdJ9Qiy0ioG4lg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k8N579f14HzBGEWvSvYE,iv:IV7USCQ2kbLHM4FQiSN0DMX5Rcto2HeTuknoQjqBF+0=,tag:AezPqTrFxNcf77ZTIFNLGA==,type:str]
    namespace: ENC[AES256_GCM,data:/ItEw1y+q+iw,iv:PHBVvJYvrEDQV+sL2DCSHDtclsk1ljHxKjwrzHMz9m0=,tag:4GhkVb0l0y1tzo4vgeVcJQ==,type:str]
type: ENC[AES256_GCM,data:cd7eYcH3,iv:MnkKVTMbR99l7L5nYiIuuNtiq1DQ6uAXQcp+hUaAxLo=,tag:TU7+1+suB5IQFVrmoocpBg==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:U7oOlvUqpP8Cs+W7djm6nBQ=,iv:VnUUDMb1BcYz3rAcpwfdGhJKClDurhgXXR9FnuHfqk8=,tag:AHLo7ftzMIV4DZsBVAmdTw==,type:str]
    clientSecret: ENC[AES256_GCM,data:+dtlPDITu/YDVLaGdO2xpXHQFzkqz3hThexN6lPI7R5ksvoFAOv7fobucZ1edIMIHPt8r0LjZo/PHpAQlCch,iv:4H/cSscpGT7RtXZOy1pVop+wq7pslqpVqqwNQCVvyDk=,tag:jH2Cfnd0KJabV5oAXEDUdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmd6KzlrbkRXd0NjLzNT
            bVB3WXpxWW1SVEdWQ05UeTJsQkpJamFCZURVCjdGN1ZsTHdHR2lXQ3NuVzZhS25G
            cVhTYWJ5Vnk5cmhMUUF1aXdoODJGeUUKLS0tIGN3WTVQSE52b1V6V0FBSm1ndUlm
            NEV0ZFRzOGF6eTc3RFR0a1lrdFNKNWsKSqicpGon1nPazincd7r3YZnvwupAeK2x
            6ZC3QbmxoSpgczJYL0ZUticrPlC52mjMh+KloX37HaYocWh6YlFs6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-10-06T00:03:36Z"
    mac: ENC[AES256_GCM,data:EzfH61eqsd9rWCKEMvvdjpLiBIhl9wMgAakMNpcUhFwWoTYjPg/eE8FiXP6zfZC+npNMmnCRWudEdB/2MaMsn3hEvBmOAnElopZ8Co1T2FQHY4VXZij9XZTAiS6txaT2OlF1wmOfFKXXbnhQ6WZZ3NfDShkBKf6TdQdRHZhRQrU=,iv:3An9SMzqgwNf48Xu6xBypuwTSSCYA3SG81nz7R+aHLQ=,tag:SwUUBqL+3AYZ7XMrcTOFpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
