apiVersion: v1
kind: Service
metadata:
  name: authentik-oidc-egress
  namespace: authentik
  annotations:
    tailscale.com/tailnet-fqdn: "https://authentik.komodo-salak.ts.net"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: https
      port: 443
      protocol: TCP
