apiVersion: ENC[AES256_GCM,data:LOo=,iv:zi7T2RJOgViUgjJscjrmHOJgf5Gk4MhdUV7qIRYbFR8=,tag:zNzlVqmUzJqEdejwMtqanA==,type:str]
kind: ENC[AES256_GCM,data:LWizejrn,iv:0+fcydK6km6J2RkDNONQpLTaUUAC/D1YwOooBRGATEs=,tag:NlF51HyBE+mkcmVrFKpPlQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ayh2KmnPOpYrr6iNsAxC,iv:YV6Z0drk6NSbPDd0St5jO8DIv0jnYwwKYJ0CHfAr3XA=,tag:+ttLCe0Lu/z2JM4iSFKatA==,type:str]
    namespace: ENC[AES256_GCM,data:l47k8996,iv:xZDsgI10OG/89nbcz48z5P3sInGLEx+hxqRiY/FpUks=,tag:AmUqgpgvRl+eHmoRVQbrzg==,type:str]
    labels:
        #ENC[AES256_GCM,data:eNyDLO47qXOT3bvCHwwBMoQHA08jfTZQyXN29Cr/bpzhInHtQne9wefeSFswd68Zo6N/uOQ=,iv:TrCGdMAoXPLd3Na2LzcyyTLoww63HI6nD+Mt4eKv0kw=,tag:jgP+hmCYL4EaukLMcZLB9w==,type:comment]
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:e9yd0g12Cn2Uiw==,iv:c0suY1AHMeX62djqABDJYSrgtfmJFQX3ljqdd+hXD6A=,tag:e+z4WBZotxVcBPmNYplh0A==,type:str]
stringData:
    type: ENC[AES256_GCM,data:ZqoZ,iv:OHCYGaSQP932BoTKCUm4w0ysdEdkD+WztJe07GoF470=,tag:RbypV55udkaF3XYZA4reVw==,type:str]
    url: ENC[AES256_GCM,data:MX0Fa2M8rowO+lvBKPOixLmlXTqgEnOYxHS1ZFjhaWveubOknUNc,iv:9rrE7tCYF69P5SUKSjvu9cRvohPjganF9CFmKNBzNPU=,tag:zS+SDwcMMfePPMlye821xg==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:g8A8Zdl2Ywo7vG/+mJ/1lgNaXSJZKpNDQ+HOtLAiNDvzdaU+u5s1pXYSZnly0JqtPT7C7vOwgRWYducQ+zCbFxhHNd6HfV2HtKZK7QsCCowcPe/qXQWMO+Dd2IuU8NkLLDJlVXuc5vd3n0ZKCN8mp19ippLEkPap0dN8aYtLtMjZTlaPVkd2UZge2Aoic/8Kk7kYwfqNv5IRc0uzLWB7Pp61trpz4WzASe/YEemYkKDbHZhlzo11FxIDga9JwmD+hqDJ+tiuWaS96H01gAN43xNNEr2zmOr4DuIg6muocb9GkbgoJM+MLzhnbDBwuMYPLpiuVmQjL7Zbm39sX6TQp3ZCJZact6Pil/yr440c0Y0uBD+eIk7LI3Wgc+36DoW4ip3aS29LtoNQer6wfvI3XkfzBtnhmBQmda5l0IKYVDE84ZmnMIcln+NRdoqtpq7NQmHQCH9L7o3wehP5Bp3s70zTNBCV95xnxtgjUU1etOigbr1LI5BxnnbwvXgOkMvkrrvGw+sjlbgFnk56FXCm6nQOsFW47Sxiy43j,iv:/Wte3FVf1WM/edLWNWdXozuC1UiGQxG78AhRKjVcwIU=,tag:+bkyEHdywYOw+qgJJQLyRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdW8rdGFMMDljdkFtSDRJ
            eDZVbzNsdzdWZkxpRVQzWUE5ZEJ3aHZNSlVZCnhzVFg4NE5BWjVRNFZWT1Q0VXJW
            RkU5c09oTnY0NUZGOTF3YmMvR3JjTmcKLS0tIEhqc1JyM2VuMVJLM0NvcHhHdStq
            d2RpZjBhWTNNVVp3c0M4Q2VTWkdYUUEK+wOd8GvYcdXU2j1J16/bkV3J3wVobf9w
            qxqZFi3ntwv2abIAnWtgKDkalpXjbEEgGcWEGdqXuF4rsCjZxw7TqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-09-28T23:50:15Z"
    mac: ENC[AES256_GCM,data:U9R9hi+q/R/U4g/T0uwNeV+C3KS2+EB1i462hSRbMCjTIhk2ytD+UCQOMg/82I8cdk6uGxuGJ/IxaVsY8wUZOuIdabrcpEL5cjHGmaTlomKlRo+zMnmHtGqWz5gTbcdqJxXHkfuDI3rTtjJRieQ7u3Bc+/6RYXrt07YgrO2vBYs=,iv:gLzfw5y0pWNTSsODoX6w58M6v+0zXdfiQEVEi87mh+w=,tag:Y7MnTobnVDw4Gp3OhcL/uQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
