apiVersion: ENC[AES256_GCM,data:ebQ=,iv:EjD7nlIGRU0Gq9FUPzFLW9EbJIaTfhXAKPPI90lGuPw=,tag:z2AjUxqqvdRTgAJRH+HClw==,type:str]
kind: ENC[AES256_GCM,data:KeeF1Lxa,iv:2rWzcyfs4oRwzcy+o5G0rZRRLVjsHM7pVs2uiPjMM0E=,tag:For/7sv+hW4/Ulpcio24Og==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Efmw21/gEU=,iv:elvO2BlzjUqGxejr/rOWVvMCW5+d+IDnGt3ugE5kaHs=,tag:URuzRonY75LoMofhhNv5tQ==,type:str]
    namespace: ENC[AES256_GCM,data:mfEmJ3Lf,iv:EoQSNbmM8ZDOX0AFtzfoFAwKti3aNJMX0jK+HAE94+o=,tag:bDaGcaNjUMOaidg/o2Kufw==,type:str]
type: ENC[AES256_GCM,data:8mCZYbE2,iv:xMWJn9oCRzJveldzoNnouDkeY58pEnU0wJNJaH4kroo=,tag:Iroid5hE004e2gp7wFqpYw==,type:str]
stringData:
    key.txt: ENC[AES256_GCM,data:kpuhGvYUiXJ0Al4F8cUvkDt9iEEKwEewtHdRykHK5tAWVwlSjIHFyN3bw2qsMid3itK2HeoOTQgDxSPCoBi1qSj00gKIL/c0Eb+n,iv:AyAAEV+5bXqYycZbSM/uQhFwnQSeslrKaegRrCdoa2w=,tag:ibAYFf46eIyqUDzojQLijA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU2lLdzVsL1pGdVJicUpU
            bGNvaE9nRWhZb3I1VTdpaWtXUHpkckl6dkdvCk1XamcwY0l1Zjh5RzE4TnkrNDlm
            TGhoWDhjSDA4T3AxdWp0TW9tZ1hNZ3cKLS0tIE5ORkZrYTNlTGdiR2dXMjZ4MHl5
            ZjlvR3hoS0o3WjdqZjZUQmJncDIySmcKgDpK6u/Jm9vCsvJCEGoEEkoc4flLPTyC
            5Gyqe12C4YC5hKzBVvWGLsolPzQ3nXoj+/GAosNkz/Ole/EmyawMwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jc9ll5h5gmcgx0sdd5ldrqcn43efafkcrn5a472f86rh7e2kcgks0rg53u
    lastmodified: "2026-10-04T18:55:18Z"
    mac: ENC[AES256_GCM,data:whc3H1o7RmapFxqjnV3uKEnicJKrjqmYi4KOYgBRm9bSfXIR5Rpkng05Ajx8n0JcjTc97Ho+zi36grfWq6BiCP8UfwiD7EA95qjpveHCvo/Pjj0Wz05SslfMwcIGVJPD8nTkV4ybzTA/ejghuXns35Jshv4hi6AvmwB2eRLnyTo=,iv:Itt6BHcYmrCZLvh9ZVvcXb1MIwtapKu2n8mv42uGR3g=,tag:L2gP5NTOtAEMIytqe3ZsCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
